[project]
name = "j1bun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "litestar[standard]>=2.15.0",
    "pydantic[email]>=2.10.6",
    "sqlalchemy>=2.0.38",
]
